Update deploy-cloudshell.yml for Azure Pipelines

diff --git a/pipelines/deploy-cloudshell.yml b/pipelines/deploy-cloudshell.yml
--- a/pipelines/deploy-cloudshell.yml
+++ b/pipelines/deploy-cloudshell.yml
@@ -4,13 +4,13 @@
 
 trigger: none
 
-# resources:
-#   pipelines:
-#   - pipeline: build
-#     project: UnifiedEdgeScenarios
-#     source: Build Cloud Shell Script
-#     trigger:
-#       enabled: true
+resources:
+  pipelines:
+  - pipeline: build
+    project: UnifiedEdgeScenarios
+    source: Build Cloud Shell Script
+    trigger:
+      enabled: true
 
 pool:
   vmImage: 'ubuntu-latest'
@@ -88,135 +88,132 @@ stages:
 
     - task: Bash@3
       enabled: true
-      displayName: 'Unzip deployment bundle file from artifacts'
-      inputs:
-        targetType: 'inline'
-        script: |
-          # Exit the script on any errors
-          set -e
-          
-          DEPLOYMENT_BUNDLE_NAME="deployment-bundle.zip"
-          
-          if [ ! -f  "$DEPLOYMENT_BUNDLE_NAME" ]; then
-          echo "The artifact does not contain \"$DEPLOYMENT_BUNDLE_NAME\" file"
-          fi
-          
-          echo "Extracting file from deployment bundle zip"
-          # Extract files to current directory
-          unzip "$DEPLOYMENT_BUNDLE_NAME" -d .
-          
-          #TODO: Add steps to ensure the zip contains the required files
-        workingDirectory: '$(System.DefaultWorkingDirectory)/deployment-bundle'
-
-    - task: Bash@3
-      enabled: true
-      displayName: 'Update values in variable.template file using pipeline variables'
+      displayName: 'Upload the deployment scripts to temporary container in storage account'
       env:
-        SP_APP_PWD: $(SP_APP_PWD)
-        EDGE_DEVICE_PASSWORD: $(EDGE_DEVICE_PASSWORD)
-        PASSWORD_FOR_WEBSITE_LOGIN: $(PASSWORD_FOR_WEBSITE_LOGIN)
-      inputs:
-        targetType: 'inline'
-        script: |
-          # Exit the inline script on any errors
-          set -e
-          
-          VARIABLES_FILE_PATH="variables.template"
-          
-          echo "Updating variables in variables.template file"
-          
-          # The following steps check the existence of the variable in the file
-          # and replace the value with in the file with the pipeline variable value using sed
-          
-          [ -v USE_INTERACTIVE_LOGIN_FOR_AZURE ] && sed -i 's#^\(USE_INTERACTIVE_LOGIN_FOR_AZURE[ ]*=\).*#\1\"$USE_INTERACTIVE_LOGIN_FOR_AZURE\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v SP_APP_ID ] && sed -i 's#^\(SP_APP_ID[ ]*=\).*#\1\"$SP_APP_ID\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v SP_APP_PWD ] && sed -i 's#^\(SP_APP_PWD[ ]*=\).*#\1\"$SP_APP_PWD\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v TENANT_ID ] && sed -i 's#^\(TENANT_ID[ ]*=\).*#\1\"$TENANT_ID\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v RESOURCE_GROUP_DEVICE ] && sed -i 's#^\(RESOURCE_GROUP_DEVICE[ ]*=\).*#\1\"$RESOURCE_GROUP_DEVICE\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v RESOURCE_GROUP_IOT ] && sed -i 's#^\(RESOURCE_GROUP_IOT[ ]*=\).*#\1\"$RESOURCE_GROUP_IOT\"#g' "$VARIABLES_FILE_PATH"
-
-          [ -v USE_EXISTING_RESOURCES ] && sed -i 's#^\(USE_EXISTING_RESOURCES[ ]*=\).*#\1\"$USE_EXISTING_RESOURCES\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v INSTALL_REQUIRED_PACKAGES ] && sed -i 's#^\(INSTALL_REQUIRED_PACKAGES[ ]*=\).*#\1\"$INSTALL_REQUIRED_PACKAGES\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v PASSWORD_FOR_WEBSITE_LOGIN ] && sed -i 's#^\(PASSWORD_FOR_WEBSITE_LOGIN[ ]*=\).*#\1\"$PASSWORD_FOR_WEBSITE_LOGIN\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v DETECTOR_MODULE_RUNTIME ] && sed -i 's#^\(DETECTOR_MODULE_RUNTIME[ ]*=\).*#\1\"$DETECTOR_MODULE_RUNTIME\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v EDGE_DEVICE_ARCHITECTURE ] && sed -i 's#^\(EDGE_DEVICE_ARCHITECTURE[ ]*=\).*#\1\"$EDGE_DEVICE_ARCHITECTURE\"#g' "$VARIABLES_FILE_PATH"
-          
-          [ -v CUSTOM_VIDEO_SOURCE ] && sed -i 's#^\(CUSTOM_VIDEO_SOURCE[ ]*=\).*#\1\"$CUSTOM_VIDEO_SOURCE\"#g' "$VARIABLES_FILE_PATH"
-          
-          echo "Updates are complete"
-        workingDirectory: '$(System.DefaultWorkingDirectory)/deployment-bundle'
-
-    - task: Bash@3
-      enabled: true
-      displayName: 'Run eye-vm-setup.sh script'
-      env:
+        RELEASE_STORAGE_ACCOUNT_KEY: $(RELEASE_STORAGE_ACCOUNT_KEY)
         SP_APP_PWD: $(SP_APP_PWD)
       inputs:
         targetType: 'inline'
         script: |
-          echo "Starting task"
-          
-          # Exit the inline script on any erros
-          set -e
-          
-          echo "Running eye-vm-sh script"
-          
-          source "./eye-vm-setup.sh"
-          
-          echo "Task is complete"
-        workingDirectory: '$(System.DefaultWorkingDirectory)/deployment-bundle'
-
-    - task: Bash@3
-      enabled: true
-      displayName: 'Run deploy-iot.sh script'
-      env:
-        SP_APP_PWD: $(SP_APP_PWD)
-        EDGE_DEVICE_PASSWORD: $(EDGE_DEVICE_PASSWORD)
-      inputs:
-        targetType: 'inline'
-        script: |
-          echo "Starting task"
-          
-          # Exit the inline script on any error
-          set -e          
-          
-          echo "Running deploy-iot script"
-
-          source "./deploy-iot.sh"
-
-          echo "Task is complete"
-        workingDirectory: '$(System.DefaultWorkingDirectory)/deployment-bundle'
-
-    - task: Bash@3
-      enabled: true
-      displayName: 'Run frontend-setup.sh script'
-      env:
-        SP_APP_PWD: $(SP_APP_PWD)
-        PASSWORD_FOR_WEBSITE_LOGIN: $(PASSWORD_FOR_WEBSITE_LOGIN)
-      inputs:
-        targetType: 'inline'
-        script: |
-          echo "Starting task"
-          
           # Exit the script on any error
           set -e
+          echo "Logging into Azure"
+          
+          az login --service-principal --username "$SP_APP_ID" --password "$SP_APP_PWD" --tenant "$TENANT_ID" --output "none"
+          
+          STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME="$RELEASE_STORAGE_ACCOUNT_TEMP_CONTAINER_NAME"
+          
+          CONTAINER=$(az storage container exists --name "$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME" --account-name "$RELEASE_STORAGE_ACCOUNT_NAME" --account-key "$RELEASE_STORAGE_ACCOUNT_KEY" -o tsv)
+          
+          if [ "$CONTAINER" == "False" ]; then
+            echo "Creating temp container \"$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME\" for arm template scripts in storage account"
+          
+            az storage container create \
+            --account-name $(RELEASE_STORAGE_ACCOUNT_NAME) \
+            --account-key $(RELEASE_STORAGE_ACCOUNT_KEY) \
+            --name "$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME"
+          
+            az storage container set-permission \
+            --account-name $(RELEASE_STORAGE_ACCOUNT_NAME) \
+            --account-key $(RELEASE_STORAGE_ACCOUNT_KEY) \
+            --name "$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME" \
+            --public-access blob
+          
+            echo "Created temp container \"$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME\" for arm template scripts in storage account"
+          fi
+          
+          az storage blob upload \
+            --account-name $(RELEASE_STORAGE_ACCOUNT_NAME) \
+            --account-key $(RELEASE_STORAGE_ACCOUNT_KEY) \
+            --container-name "$STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME" \
+            --file deployment-bundle.zip \
+            --name deployment-bundle.zip
+          
+          unzip deployment-bundle.zip -d .
+        workingDirectory: '$(System.DefaultWorkingDirectory)/deployment-bundle'
+    
+    - task: Bash@3
+      enabled: true
+      displayName: 'Prerequisite software installation'
+      inputs:
+        targetType: 'inline'
+        script: |
+          apt install -y curl
+          apt install -y jq
+          apt install -y timeout
+          apt install -y wget
+          apt install -y sshpass
 
-          cd deployment-bundle
+          if [[ $(az extension list --query "[?name=='azure-iot'].name" --output tsv | wc -c) -eq 0 ]]; then
+              echo "$(info) Installing azure-iot extension"
+              az extension add --name azure-iot
+          fi
+
+          INSTALL_AZCOPY="true"
+          if [ -n "$(command -v azcopy)" ]; then
+              currentVersion=$(sudo azcopy --version | cut -d ' ' -f3)
+              requiredVersion="10.5.1"
+              # Sort the current version and required version to get the lowest of the two and then then compare it with required version
+              if [ "$(printf '%s\n' "$currentVersion" "$requiredVersion" | sort -V | head -n1)" == "$requiredVersion" ]; then
+                  # Current installed azcopy version is higher than required, no need to re-install
+                  INSTALL_AZCOPY="false"
+              fi
+          fi
+  
+          if [ "$INSTALL_AZCOPY" == "true" ]; then
+  
+              echo "$(info) Installing AzCopy"
+  
+              CURRENT_DIRECTORY="$PWD"
+              wget https://aka.ms/downloadazcopy-v10-linux -O downloadazcopy-v10-linux
+              # unzipping the downloaded archive
+              tar -xvf downloadazcopy-v10-linux
+              # changing directory to fetch the azcopy executable
+              cd azcopy_linux*/
+              # Add azcopy to /usr/bin directory
+              sudo cp azcopy /usr/bin/
+              # Return to original directory
+              cd "$CURRENT_DIRECTORY"
+              # Remove the downloaded files
+              rm azcopy_linux* -r
+              rm downloadazcopy-v10-linux
+  
+              echo "$(info) Installed AzCopy "
+          fi
+        workingDirectory: 'System.DefaultWorkingDirectory'
+
+    - task: Bash@3
+      enabled: true
+      displayName: 'Run cloudshell-deployment.sh script'
+      env:
+        SP_APP_PWD: $(SP_APP_PWD)
+      inputs:
+        targetType: 'inline'
+        script: |
+          echo "Starting task"
+
+          echo "Updating sas url for deployment bundle zip"
+          SCRIPTS_URL="https://${RELEASE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${STORAGE_ACCOUNT_CLOUDSHELL_SCRIPTS_CONTAINER_NAME}/deployment-bundle.zip"
+          sed -i 's#^\(SAS_URL[ ]*=\).*#\1\"'"$SCRIPTS_URL"'\"#g' "cloudshell-deployment.sh"
+          echo "Updated sas url for deployment bundle zip"
+
+          # Exit the inline script on any erros
+          set -e
+
+          echo "Setting the distribution envrionment to cloudshell for skipping login step"
+          POWERSHELL_DISTRIBUTION_CHANNEL="CloudShell"
+          export POWERSHELL_DISTRIBUTION_CHANNEL
+
+          echo "Logging into Azure"
           
-          echo "Running frontend-setup script"
+          az login --service-principal --username "$SP_APP_ID" --password "$SP_APP_PWD" --tenant "$TENANT_ID" --output "none"
+
+          echo "Running cloudshell-deployment.sh script"
           
-          source "./frontend-setup.sh"
+          sudo "./cloudshell-deployment.sh"
           
           echo "Task is complete"
+        workingDirectory: '$(System.DefaultWorkingDirectory)/CloudshellDeployment-Scripts'
 
 
     - task: Bash@3
